language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

install:
    - composer install --dev --no-interaction --prefer-source

script:
    - vendor/bin/php-cs-fixer fix -v --dry-run src/
    - vendor/bin/phpunit -c phpunit.xml.dist --colors --coverage-clover=coverage.clover
after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
notifications:
  hipchat: 365ed34e4a590ff19b44a44bf08619@1963196